---
#
# Setup the server. Works for Docker and real servers.
#
# - install packages
# - setup postgresql user & database
#
# *** FIXME: postgresql hba uses 'trust'
#            it's ok for Docker development environment, but it's
#            insecure for real servers
#
# *** FIXME: remove '_dev' suffix from postgresql db and username
#            it's ok for Docker development environment, but it's
#            confusing for real servers
#
- name: register extra repositories
  sudo: yes
  copy: src=pgdg.list dest=/etc/apt/sources.list.d
  tags:
    - apt
    - setup

- name: upload extra repositories keys
  sudo: yes
  copy: src=ACCC4CF8.asc dest=/tmp/
  tags:
    - apt
    - setup

- name: register extra repositories keys
  sudo: yes
  command: sudo apt-key add /tmp/ACCC4CF8.asc
  tags:
    - apt
    - setup

- name: update apt
  apt: update_cache=yes
  sudo: yes
  tags:
    - apt
    - setup
    - update_apt

- name: install packages
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - git
    - rsync
    - python3.4
    - python3.4-dev
    - python-virtualenv
    - postgresql-9.4
    - postgresql-client-9.4
    - postgresql-contrib-9.4
    - libpq-dev
    - postgresql-server-dev-9.4
    - python-psycopg2
  tags:
    - apt
    - setup

- name: initialize postgresql
  sudo: yes
  command: pg_createcluster 9.4 main creates=/var/lib/postgresql/9.4/main
  tags:
    - setup

- name: setup postgresql config
  sudo: yes
  lineinfile: >
    dest=/etc/postgresql/9.4/main/postgresql.conf
    regexp=^include_if_exists
    line="include_if_exists = '/etc/postgresql/9.4/main/postgresql-customizations.conf'"
  notify:
    - reload postgres
  tags:
    - setup

- name: upload postgresql config
  sudo: yes
  copy: >
    src={{item}}
    dest=/etc/postgresql/9.4/main/{{item}}
    owner=postgres
  with_items:
    - postgresql-customizations.conf
    - pg_hba.conf
  notify:
    - reload postgres
  tags:
    - setup

- name: upload postgresql startup
  sudo: yes
  copy: src=supervisor-postgresql.conf dest=/etc/supervisor/conf.d/
  notify:
    - reload postgres
  tags:
    - setup

- name: flush handlers to reload postgresql
  meta: flush_handlers
  tags:
    - setup

- name: create pg user
  postgresql_user: name=lumina_dev password=lumina_dev
  tags:
    - setup

- name: create pg db
  postgresql_db: name=lumina_dev owner=lumina_dev
  tags:
    - setup
