---
- name: register extra repositories
  sudo: yes
  copy: src=pgdg.list dest=/etc/apt/sources.list.d
  tags:
    - setup
    - pg

- name: upload extra repositories keys
  sudo: yes
  copy: src=ACCC4CF8.asc dest=/tmp/
  tags:
    - setup
    - pg

- name: register extra repositories keys
  sudo: yes
  command: sudo apt-key add /tmp/ACCC4CF8.asc
  tags:
    - setup
    - pg

- name: update apt
  apt: update_cache=yes
  sudo: yes
  tags:
    - update_apt
    - setup

- name: install packages
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - git
    - rsync
    - python3.4
    - python3.4-dev
    - python-virtualenv
    - postgresql-9.4
    - postgresql-client-9.4
    - postgresql-contrib-9.4
    - libpq-dev
    - postgresql-server-dev-9.4
  tags:
    - setup

- name: make directories
  file: path=/home/lumina/{{item}} owner=lumina group=lumina mode=0700 state=directory
  sudo: yes
  with_items:
    - .pip
    - deploy
    - deploy/src
    - deploy/local
    - deploy/.pip-cache

- name: setup pip
  ini_file: >
    dest=/home/lumina/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/lumina/deploy/.pip-cache'
  tags:
    - setup

- name: upload sources
  synchronize: >
    src=../lumina
    dest=/home/lumina/deploy/src
    rsync_opts=--exclude=.git

- name: upload other files
  copy: >
    src=../requirements.txt
    dest=/home/lumina/deploy/src/

- name: create virtualenv
  command: virtualenv -p python3.4 /home/lumina/deploy/virtualenv creates=/home/lumina/deploy/virtualenv/bin/python

- name: setup virtualenv
  pip: >
    requirements=/home/lumina/deploy/src/requirements.txt
    virtualenv=/home/lumina/deploy/virtualenv
    virtualenv_site_packages=no
    virtualenv_command=/usr/bin/python3.4
    extra_args='-U'
