#
# http://about.travis-ci.org/docs/user/languages/python/
#
language: python
python:
 - "2.7"
install:
 - "pip install -q -r requirements-travis-ci.txt --use-mirrors"
script: "python manage.py test lumina"
