---
- name: make directories
  file: path=/home/lumina/{{item}} owner=lumina group=lumina mode=0700 state=directory
  sudo: yes
  with_items:
    - .pip
    - deploy
    - deploy/src
    - deploy/local
    - deploy/.pip-cache

- name: setup pip
  ini_file: >
    dest=/home/lumina/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/lumina/deploy/.pip-cache'
  tags:
    - setup

- name: upload sources
  synchronize: >
    src=../lumina
    dest=/home/lumina/deploy/src
    rsync_opts=--exclude=.git

- name: upload other files
  copy: >
    src=../requirements.txt
    dest=/home/lumina/deploy/src/

- name: create virtualenv
  command: virtualenv -p python3.4 /home/lumina/deploy/virtualenv creates=/home/lumina/deploy/virtualenv/bin/python

- name: setup virtualenv
  pip: >
    requirements=/home/lumina/deploy/src/requirements.txt
    virtualenv=/home/lumina/deploy/virtualenv
    virtualenv_site_packages=no
    virtualenv_command=/usr/bin/python3.4
    extra_args='-U'
