---
#
# Install Lumina
#
# - setup pip, virtualenv
# - upload sources
#
# *** TODO: sync DB
# *** TODO: upload settings.py
# *** TODO: init script for lumina
#
- name: make directories
  file: path=/home/lumina/{{item}} owner=lumina group=lumina mode=0700 state=directory
  sudo: yes
  with_items:
    - .pip
    - deploy
    - deploy/.pip-cache
    - deploy/local
    - deploy/log
    - deploy/media
    - deploy/run
    - deploy/static
    - deploy/src
    - deploy/src-other

- name: setup pip
  ini_file: >
    dest=/home/lumina/.pip/pip.conf
    section=install
    option='download-cache'
    value='/home/lumina/deploy/.pip-cache'
  tags:
    - setup
    - virtualenv

- name: upload / synchronize sources
  synchronize: >
    src=../lumina
    dest=/home/lumina/deploy/src
    rsync_opts=--exclude=.git,--delete,--delete-after
  tags:
    - quick

- name: upload other files related to sources
  copy: >
    src={{item}}
    dest=/home/lumina/deploy/src-other/
  with_items:
    - ../requirements.txt
    - ../manage.py
    - manage.sh
  tags:
    - virtualenv

- name: create virtualenv
  command: >
    virtualenv -p python3.4 /home/lumina/deploy/virtualenv
    creates=/home/lumina/deploy/virtualenv/bin/python
  tags:
    - virtualenv

- name: setup virtualenv
  pip: >
    requirements=/home/lumina/deploy/src-other/requirements.txt
    virtualenv=/home/lumina/deploy/virtualenv
    virtualenv_site_packages=no
    virtualenv_command=/usr/bin/python3.4
    extra_args='-U'
  tags:
    - virtualenv

- name: upload lumina settings
  template: >
    src=lumina_local_settings.py
    dest=/home/lumina/deploy/src-other/lumina_local_settings.py
  tags:
    - quick

- name: syncdb
  django_manage: >
      app_path=/home/lumina/deploy/src-other
      command=syncdb
      settings=lumina.settings
      virtualenv=/home/lumina/deploy/virtualenv
  environment:
    PYTHONPATH: '/home/lumina/deploy/src:/home/lumina/deploy/src-other:/home/lumina/deploy/local'
  tags:
    - quick

- name: collectstatic
  django_manage: >
      app_path=/home/lumina/deploy/src-other
      command=collectstatic
      settings=lumina.settings
      virtualenv=/home/lumina/deploy/virtualenv
  environment:
    PYTHONPATH: '/home/lumina/deploy/src:/home/lumina/deploy/src-other:/home/lumina/deploy/local'
  tags:
    - quick

- name: upload uwsgi.ini
  template: >
    src=uwsgi.ini
    dest=/home/lumina/deploy/local/uwsgi.ini
  notify:
    - reload uwsgi from supervisord

- name: upload supervisord config for uwsgi
  sudo: yes
  copy: src=supervisor-uwsgi.conf dest=/etc/supervisor/conf.d/
  notify:
    - reload uwsgi from supervisord

- name: reload uwsgi
  command: /bin/true
  notify:
    - reload uwsgi
  # FIXME: if uwsgi isn't running, this task doesn't start it
