"""
Generated by 'django-admin startproject' using Django 1.8.
https://docs.djangoproject.com/en/1.8/topics/settings/
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# ===== Lumina =====

# Dump object with {% dump_objects %}
LUMINA_DUMP_OBJECTS = False

# ===== Django =====

# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

AUTH_USER_MODEL = 'lumina.LuminaUser'

DEBUG = False

DATETIME_FORMAT = 'd/m/Y - H:i'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# DATABASES = (...)

# ALLOWED_HOSTS = (...)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

STATIC_URL = '/static/'

# MEDIA_ROOT = (...)

MEDIA_URL = ''

STATIC_ROOT = ''

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'lumina.middleware.LoggingMiddleware',
)

ROOT_URLCONF = 'lumina.urls'

WSGI_APPLICATION = 'lumina.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # ----- Django 1.8 defaults
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # ----- Migrated from old config / Django 1.5
                "django.core.context_processors.i18n",
                "django.core.context_processors.media",
                "django.core.context_processors.static",
                "django.core.context_processors.tz",
            ],
        },
    },
]

INSTALLED_APPS = (
    # ----- Django 1.8 defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ----- Migrated from old config / Django 1.5
    'django.contrib.humanize',
    # 'localflavor',
    # 'cities_light',
    'autocomplete_light',
    'crispy_forms',
    'lumina',
    'mailer',
)

LOGIN_REDIRECT_URL = 'home'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

# ===== Selenium =====

SELENIUM_WEBDRIVER_BIN = (
    # Ubuntu 13.04 - Package: 'chromium-chromedriver'
    '/usr/lib/chromium-browser/chromedriver',
)


# ===== Crispy forms =====

CRISPY_TEMPLATE_PACK = "bootstrap3"


# ===== Local settings =====

# Load settings from 'lumina_local_settings'
try:
    from lumina_local_settings import *  # noqa
except ImportError as e:
    import warnings
    warnings.warn("Couldn't import from 'lumina_local_settings': %s" % e.args[0], stacklevel=0)
